// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.elasticpath.test.factory;

import com.elasticpath.common.dto.AddressDTO;
import com.elasticpath.common.dto.customer.AttributeValueDTO;
import com.elasticpath.common.dto.customer.CreditCardDTO;
import com.elasticpath.common.dto.customer.CustomerDTO;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

public class CustomerDTOBuilder extends CustomerDTOBuilderBase<CustomerDTOBuilder> {
	public static CustomerDTOBuilder newCustomerDTO() {
		return new CustomerDTOBuilder();
	}

	public CustomerDTOBuilder() {
		super(new CustomerDTO());
	}

	public CustomerDTO build() {
		return getInstance();
	}
}

@SuppressWarnings({ "unchecked", "PMD.TooManyMethods" })
class CustomerDTOBuilderBase<GeneratorT extends CustomerDTOBuilderBase<GeneratorT>> {
	private final CustomerDTO instance;

	protected CustomerDTOBuilderBase(final CustomerDTO aInstance) {
		instance = aInstance;
	}

	protected CustomerDTO getInstance() {
		return instance;
	}

	public GeneratorT withGuid(final String aValue) {
		instance.setGuid(aValue);

		return (GeneratorT) this;
	}

	public GeneratorT withUserId(final String aValue) {
		instance.setUserId(aValue);

		return (GeneratorT) this;
	}

	public GeneratorT withStoreCode(final String aValue) {
		instance.setStoreCode(aValue);

		return (GeneratorT) this;
	}

	public GeneratorT withStatus(final int aValue) {
		instance.setStatus(aValue);

		return (GeneratorT) this;
	}

	public GeneratorT withCreationDate(final Date aValue) {
		instance.setCreationDate(aValue);

		return (GeneratorT) this;
	}

	public GeneratorT withLastEditDate(final Date aValue) {
		instance.setLastEditDate(aValue);

		return (GeneratorT) this;
	}

	public GeneratorT withPassword(final String aValue) {
		instance.setPassword(aValue);

		return (GeneratorT) this;
	}

	public GeneratorT withAddresses(final List<AddressDTO> aValue) {
		instance.setAddresses(aValue);

		return (GeneratorT) this;
	}

	public GeneratorT withAddedAddress(final AddressDTO aValue) {
		if (instance.getAddresses() == null) {
			instance.setAddresses(new ArrayList<AddressDTO>());
		}

		instance.getAddresses().add(aValue);

		return (GeneratorT) this;
	}

	public AddedAddressAddressDTOBuilder withAddedAddress() {
		AddressDTO obj = new AddressDTO();

		withAddedAddress(obj);

		return new AddedAddressAddressDTOBuilder(obj);
	}

	public GeneratorT withGroups(final List<String> aValue) {
		instance.setGroups(aValue);

		return (GeneratorT) this;
	}

	public GeneratorT withAddedGroup(final String aValue) {
		if (instance.getGroups() == null) {
			instance.setGroups(new ArrayList<String>());
		}

		instance.getGroups().add(aValue);

		return (GeneratorT) this;
	}

	public GeneratorT withPreferredShippingAddressGuid(final String aValue) {
		instance.setPreferredShippingAddressGuid(aValue);

		return (GeneratorT) this;
	}

	public GeneratorT withPreferredBillingAddressGuid(final String aValue) {
		instance.setPreferredBillingAddressGuid(aValue);

		return (GeneratorT) this;
	}

	public GeneratorT withCreditCards(final List<CreditCardDTO> aValue) {
		instance.setCreditCards(aValue);

		return (GeneratorT) this;
	}

	public GeneratorT withAddedCreditCard(final CreditCardDTO aValue) {
		if (instance.getCreditCards() == null) {
			instance.setCreditCards(new ArrayList<CreditCardDTO>());
		}

		instance.getCreditCards().add(aValue);

		return (GeneratorT) this;
	}

	public AddedCreditCardCreditCardDTOBuilder withAddedCreditCard() {
		CreditCardDTO obj = new CreditCardDTO();

		withAddedCreditCard(obj);

		return new AddedCreditCardCreditCardDTOBuilder(obj);
	}

	public GeneratorT withProfileValues(final Set<AttributeValueDTO> aValue) {
		instance.setProfileValues(aValue);

		return (GeneratorT) this;
	}

	public GeneratorT withAddedProfileValue(final AttributeValueDTO aValue) {
		if (instance.getProfileValues() == null) {
			instance.setProfileValues(new HashSet<AttributeValueDTO>());
		}

		instance.getProfileValues().add(aValue);

		return (GeneratorT) this;
	}

	public GeneratorT withSalt(final String aValue) {
		instance.setSalt(aValue);

		return (GeneratorT) this;
	}

	public class AddedAddressAddressDTOBuilder extends AddressDTOBuilderBase<AddedAddressAddressDTOBuilder> {
		public AddedAddressAddressDTOBuilder(final AddressDTO aInstance) {
			super(aInstance);
		}

		public GeneratorT endAddress() {
			return (GeneratorT) CustomerDTOBuilderBase.this;
		}
	}

	public class AddedCreditCardCreditCardDTOBuilder extends CreditCardDTOBuilderBase<AddedCreditCardCreditCardDTOBuilder> {
		public AddedCreditCardCreditCardDTOBuilder(final CreditCardDTO aInstance) {
			super(aInstance);
		}

		public GeneratorT endCreditCard() {
			return (GeneratorT) CustomerDTOBuilderBase.this;
		}
	}

	public static class AddressDTOBuilderBase<GeneratorT extends AddressDTOBuilderBase<GeneratorT>> {
		private final AddressDTO instance;

		protected AddressDTOBuilderBase(final AddressDTO aInstance) {
			instance = aInstance;
		}

		protected AddressDTO getInstance() {
			return instance;
		}

		public GeneratorT withGuid(final String aValue) {
			instance.setGuid(aValue);

			return (GeneratorT) this;
		}

		public GeneratorT withLastName(final String aValue) {
			instance.setLastName(aValue);

			return (GeneratorT) this;
		}

		public GeneratorT withFirstName(final String aValue) {
			instance.setFirstName(aValue);

			return (GeneratorT) this;
		}

		public GeneratorT withPhoneNumber(final String aValue) {
			instance.setPhoneNumber(aValue);

			return (GeneratorT) this;
		}

		public GeneratorT withFaxNumber(final String aValue) {
			instance.setFaxNumber(aValue);

			return (GeneratorT) this;
		}

		public GeneratorT withStreet1(final String aValue) {
			instance.setStreet1(aValue);

			return (GeneratorT) this;
		}

		public GeneratorT withStreet2(final String aValue) {
			instance.setStreet2(aValue);

			return (GeneratorT) this;
		}

		public GeneratorT withCity(final String aValue) {
			instance.setCity(aValue);

			return (GeneratorT) this;
		}

		public GeneratorT withSubCountry(final String aValue) {
			instance.setSubCountry(aValue);

			return (GeneratorT) this;
		}

		public GeneratorT withZipOrPostalCode(final String aValue) {
			instance.setZipOrPostalCode(aValue);

			return (GeneratorT) this;
		}

		public GeneratorT withCountry(final String aValue) {
			instance.setCountry(aValue);

			return (GeneratorT) this;
		}

		public GeneratorT withCommercialAddress(final boolean aValue) {
			instance.setCommercialAddress(aValue);

			return (GeneratorT) this;
		}
	}

	public static class CreditCardDTOBuilderBase<GeneratorT extends CreditCardDTOBuilderBase<GeneratorT>> {
		private final CreditCardDTO instance;

		protected CreditCardDTOBuilderBase(final CreditCardDTO aInstance) {
			instance = aInstance;
		}

		protected CreditCardDTO getInstance() {
			return instance;
		}

		public GeneratorT withCardType(final String aValue) {
			instance.setCardType(aValue);

			return (GeneratorT) this;
		}

		public GeneratorT withExpiryYear(final String aValue) {
			instance.setExpiryYear(aValue);

			return (GeneratorT) this;
		}

		public GeneratorT withExpiryMonth(final String aValue) {
			instance.setExpiryMonth(aValue);

			return (GeneratorT) this;
		}

		public GeneratorT withCardHolderName(final String aValue) {
			instance.setCardHolderName(aValue);

			return (GeneratorT) this;
		}

		public GeneratorT withStartYear(final String aValue) {
			instance.setStartYear(aValue);

			return (GeneratorT) this;
		}

		public GeneratorT withStartMonth(final String aValue) {
			instance.setStartMonth(aValue);

			return (GeneratorT) this;
		}

		public GeneratorT withIssueNumber(final Integer aValue) {
			instance.setIssueNumber(aValue);

			return (GeneratorT) this;
		}

		public GeneratorT withDefaultCard(final boolean aValue) {
			instance.setDefaultCard(aValue);

			return (GeneratorT) this;
		}

		public GeneratorT withBillingAddressGuid(final String aValue) {
			instance.setBillingAddressGuid(aValue);

			return (GeneratorT) this;
		}

		public GeneratorT withCardNumber(final String aValue) {
			instance.setCardNumber(aValue);

			return (GeneratorT) this;
		}

		public GeneratorT withGuid(final String aValue) {
			instance.setGuid(aValue);

			return (GeneratorT) this;
		}
	}
}
